databases:
  - name: expense-tracker-db
    databaseName: expensetracker
    user: expensetracker
    plan: free

services:
  - type: web
    name: expense-tracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn expense_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.11"
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString

          
print("DATABASE ENGINE:", DATABASES["default"]["ENGINE"])
print("DATABASE NAME:", DATABASES["default"].get("NAME"))