services:
  - type: web
    name: expense-tracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn expense_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.11"