# Generated by Django 5.2.13 on 2026-04-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_passwordsetuptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('home', 'Home'), ('couple', 'Couple'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='tracker.GroupMember', to='tracker.friend'),
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together={('group', 'email')},
        ),
    ]
